---
abstract: 'Dancer2 Plugin to create multilanguage sites'
author:
  - "Simone Fare' <cymon@tiscali.it>"
build_requires:
  Dancer2: 0
  FindBin: 0
  LWP::UserAgent: 0
  Test::More: 0
  Test::TCP: 0
  lib: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-Multilang
requires:
  Dancer2::Plugin: 0.156000
resources:
  repository: https://github.com/cym0n/Dancer2-Plugin-Multilang.git
version: 1.1.0
